#!/usr/bin/with-contenv bash
# shellcheck shell=bash

lsiown abc:abc \
    /config

lsiown -R abc:abc \
    /app/www/bootstrap/cache \
    /app/www/storage \
    /app/www/database

# Clear old cache
s6-setuidgid abc php /app/www/artisan optimize:clear --no-ansi -q

if [[ ${DB_CONNECTION:="sqlite"} = "sqlite" ]]; then
    # create symlinks
    symlinks=( \
    /app/www/database/database.sqlite \
    )

    for i in "${symlinks[@]}"
    do
        if [[ -e "$i" && ! -L "$i" ]]; then
            rm -rf "$i"
        fi
        if [[ ! -L "$i" ]]; then
            ln -s /config/"$(basename "$i")" "$i"
        fi
    done
fi

# Check for env file
if [[ ! -f /config/.env ]]; then
    cp /app/www/.env.production /config/.env
fi

# create symlinks
symlinks=( \
/app/www/.env \
)

for i in "${symlinks[@]}"
do
    if [[ -e "$i" && ! -L "$i" ]]; then
        rm -rf "$i"
    fi
    if [[ ! -L "$i" ]]; then
        ln -s /config/"$(basename "$i")" "$i"
    fi
done

# Check for app key
if [[ -z ${APP_KEY} ]]; then
    if ! grep -E "APP_KEY=[0-9A-Za-z:+\/=]{1,}" /app/www/.env > /dev/null; then
        export APP_KEY=$(s6-setuidgid abc php /app/www/artisan key:generate --show)
        echo "An application key was generated at start up, as no environment variable was set."
        echo "To set an application key that persists, read the docs: https://docs.speedtest-tracker.dev/"
    fi
fi

# Build cache
s6-setuidgid abc php /app/www/artisan view:clear --no-ansi -q
s6-setuidgid abc php /app/www/artisan optimize --no-ansi -q

# Migrate database
s6-setuidgid abc php /app/www/artisan migrate --force --no-ansi -q

lsiown -R abc:abc \
    /config
