name: Build ARMv7

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-armhf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build ARMv7 image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.armhf
          platforms: linux/arm/v7
          push: false
